# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title:            "数域K上N维线性空间"
description:      "This is a personal blog of Ruizhengyu on Github Pages."
url:              https://ruizhengyu.github.io
enforce_ssl:      ruizhengyu.github.io

repo:             https://github.com/ruizhengyu/ruizhengyu.github.io
disqus_name:      "ruizhengyu"
disqus_site_name: "Ruizhengyu's Blog"
cnd:              

# Author settings
author:
  name:       "Ruizhengyu"
  first_name: "Rui"
  email:      ruizhengyu@gmail.com
  url:        https://ruizhengyu.github.io
  github:     https://github.com/ruizhengyu
  weibo:      http://weibo.com/u/2237065581
  zhihu:      https://www.zhihu.com/people/ruizhengyu

# Build settings
permalink:    /:year/:month/:day/:title/
markdown:     kramdown
highlighter:  rouge

sass:
  style: compressed
  
paginate_path:  /blog/page/:num/

gems:
  - jekyll-seo-tag

BASE_PATH:  https://ruizhengyu.github.io

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html
messages_path: messages.html
archive_path: archive.html
